/**
Problem Statement:
Write a query to list down all the movies along with their details that have keywords like 'sport' or 'sequel' or 'suspense'.

Note:

Return the columns 'original_title', 'director', 'genres', 'cast', 'budget', 'revenue', 'runtime', and 'vote_average'.
Return the columns ordered by original_title in ascending order.
Dataset description for 'movies' table:

id - tmdb movie id
imdb_id - imdb movie id
popularity - A numeric quantity specifying the movie popularity.
budget - The budget in which the movie was made.
revenue - The worldwide revenue generated by the movie.
original_title - The title of the movie
cast - The name of the lead and supporting actors.
homepage - A link to the homepage of the movie.
director - The name of the director of the movie
tagline - Movie tagline.
keywords - The keywords or tags related to the movie.
overview - A brief description of the movie.
runtime - The running time of the movie in minutes.
genres - The genres of the movies
production_companies - The production house of the movie.
release_date - the date on which it was released.
vote_count - the count of votes received.
vote_average - average ratings the movie received.
release_year - the year in which it was released.
**/
SELECT original_title, director, genres, cast, budget, revenue, runtime, vote_average
FROM movies
where keywords like '%sport%' OR keywords LIKE '%sequel%' OR keywords LIKE '%suspense%'
order by original_title 
